version: "3.9"

services:
  bench:
    image: jamesmishra.com/babycat
    build:
      context: .
      args:
        RUST_VERSION: 1.67.1
        PYTHON_VERSION: 3.10.10
        MATURIN_VERSION: 0.14.3

  jupyter:
    image: jamesmishra.com/babycat
    entrypoint: jupyter-lab
    command:
      - --no-browser
      - --ip=0.0.0.0
      - --port=8888
      - --allow-root
    user: root
    environment:
      JUPYTER_TOKEN: changeme
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/notebooks
    working_dir: /notebooks